-- MySQL Script generated by MySQL Workbench
-- Wed Mar 26 21:19:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Peliculas_TMDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Peliculas_TMDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Peliculas_TMDb` ;
USE `Peliculas_TMDb` ;

-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Etiquetas` (
  `id_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_etiqueta`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Idiomas` (
  `id_idioma` VARCHAR(2) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_idioma`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Peliculas` (
  `id_pelicula` INT NOT NULL,
  `titulo` VARCHAR(225) NULL,
  `fecha_estreno` DATE NULL,
  `presupuesto` BIGINT(10) NULL,
  `ingresos` BIGINT(10) NULL,
  `duracion` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `enlace` VARCHAR(200) NULL,
  `idioma_original` VARCHAR(2) NULL,
  `popularidad` FLOAT NULL,
  `estatus` VARCHAR(50) NULL,
  `eslogan` VARCHAR(100) NULL,
  `titulooriginal` VARCHAR(255) NULL,
  `media_votos` FLOAT NULL,
  `numero_votos` INT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `FK_Peliiculas_Idioma_idx` (`idioma_original` ASC) VISIBLE,
  CONSTRAINT `FK_Peliiculas_Idioma`
    FOREIGN KEY (`idioma_original`)
    REFERENCES `Peliculas_TMDb`.`Idiomas` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Usuarios` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(100) NULL,
  `correo_electronico` VARCHAR(255) NULL,
  `contrasena_hash` VARCHAR(255) NULL,
  `rol` VARCHAR(10) NULL,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Favoritos` (
  `id_usuario` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_pelicula`),
  INDEX `FK_Favoritos_Pelicula` (`id_pelicula` ASC) VISIBLE,
  CONSTRAINT `FK_Favoritos_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`),
  CONSTRAINT `FK_Favoritos_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Peliculas_TMDb`.`Usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genero`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Lista` (
  `id_lista` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_pelicula` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lista`),
  INDEX `FK_Lista_Pelicula` (`id_pelicula` ASC) VISIBLE,
  INDEX `FK_Lista_Usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_Lista_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`),
  CONSTRAINT `FK_Lista_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Peliculas_TMDb`.`Usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`MiembroReparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`MiembroReparto` (
  `id_personaje` INT NULL DEFAULT NULL,
  `personaje` VARCHAR(50) NULL DEFAULT NULL,
  `id_credencial` VARCHAR(50) NULL DEFAULT NULL,
  `genero` INT NULL DEFAULT NULL,
  `id_miembro` INT NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_miembro`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`PaisProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`PaisProduccion` (
  `id_pais` VARCHAR(2) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pais`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Etiqueta` (
  `id_pelicula` INT NOT NULL,
  `id_etiqueta` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_etiqueta`),
  INDEX `FK_Pelicula_Etiqueta_Etiquetas` (`id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Etiqueta_Etiquetas`
    FOREIGN KEY (`id_etiqueta`)
    REFERENCES `Peliculas_TMDb`.`Etiquetas` (`id_etiqueta`),
  CONSTRAINT `FK_Pelicula_Etiqueta_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Genero` (
  `id_pelicula` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_genero`),
  INDEX `FK_Pelicula_Genero_Generos` (`id_genero` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Genero_Generos`
    FOREIGN KEY (`id_genero`)
    REFERENCES `Peliculas_TMDb`.`Generos` (`id_genero`),
  CONSTRAINT `FK_Pelicula_Genero_Peliculas`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Idioma` (
  `id_pelicula` INT NOT NULL,
  `id_idioma` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_idioma`),
  INDEX `FK_Pelicula_Idioma_Idiomas` (`id_idioma` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Idioma_Idiomas`
    FOREIGN KEY (`id_idioma`)
    REFERENCES `Peliculas_TMDb`.`Idiomas` (`id_idioma`),
  CONSTRAINT `FK_Pelicula_Idioma_Peliculas`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Personal` (
  `id_personal` INT NOT NULL,
  `id_credencial` VARCHAR(50) NULL,
  `departamento` VARCHAR(50) NULL,
  `genero` INT NULL,
  `trabajo` VARCHAR(50) NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id_personal`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Crew` (
  `id_pelicula` INT NOT NULL,
  `id_miembro` INT NOT NULL,
  `id_personal` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_miembro`, `id_personal`),
  INDEX `FK_Crew_MiembroReparto` (`id_miembro` ASC) VISIBLE,
  INDEX `FK_Pelicula_Personal_idx` (`id_personal` ASC) VISIBLE,
  CONSTRAINT `FK_Crew_MiembroReparto`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `Peliculas_TMDb`.`MiembroReparto` (`id_miembro`),
  CONSTRAINT `FK_Crew_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`),
  CONSTRAINT `FK_Crew_Personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `Peliculas_TMDb`.`Personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_PaisProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_PaisProduccion` (
  `id_pelicula` INT NOT NULL,
  `id_pais` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_pais`),
  INDEX `FK_Pelicula_PaisProduccion` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_PaisProduccion`
    FOREIGN KEY (`id_pais`)
    REFERENCES `Peliculas_TMDb`.`PaisProduccion` (`id_pais`),
  CONSTRAINT `FK_Pelicula_pelPais`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Productoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Productoras` (
  `id_productora` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id_productora`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Productora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Productora` (
  `id_pelicula` INT NOT NULL,
  `id_productora` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_productora`),
  INDEX `FK_Pelicula_Productora` (`id_productora` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Productora`
    FOREIGN KEY (`id_productora`)
    REFERENCES `Peliculas_TMDb`.`Productoras` (`id_productora`),
  CONSTRAINT `FK_Pelicula_Pelicula_Productora`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`));

USE `Peliculas_TMDb` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `Peliculas_TMDb`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
