-- MySQL Script generated by MySQL Workbench
-- Sun Mar 30 20:41:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Peliculas_TMDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Peliculas_TMDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Peliculas_TMDb` ;
USE `Peliculas_TMDb` ;

-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Etiquetas` (
  `id_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_etiqueta`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Idiomas` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_idioma`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Peliculas` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(225) NULL,
  `fecha_estreno` DATE NULL,
  `presupuesto` BIGINT(10) NULL,
  `ingresos` BIGINT(10) NULL,
  `duracion` INT NULL,
  `descripcion` VARCHAR(500) NULL,
  `enlace` VARCHAR(200) NULL,
  `idioma_original` INT NULL,
  `popularidad` FLOAT NULL,
  `estatus` VARCHAR(50) NULL,
  `eslogan` VARCHAR(100) NULL,
  `titulooriginal` VARCHAR(255) NULL,
  `media_votos` FLOAT NULL,
  `numero_votos` INT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `FK_Peliiculas_Idioma_idx` (`idioma_original` ASC) VISIBLE,
  CONSTRAINT `FK_Peliculas_Idioma`
    FOREIGN KEY (`idioma_original`)
    REFERENCES `Peliculas_TMDb`.`Idiomas` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NULL,
  `correo_electronico` VARCHAR(255) NULL,
  `contrasena_hash` VARCHAR(255) NULL,
  `rol` VARCHAR(10) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Favoritos` (
  `id_usuario` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_pelicula`),
  INDEX `FK_Favoritos_Pelicula` (`id_pelicula` ASC) VISIBLE,
  CONSTRAINT `FK_Favoritos_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`),
  CONSTRAINT `FK_Favoritos_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Peliculas_TMDb`.`Usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_genero`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Lista` (
  `id_lista` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lista`),
  INDEX `FK_Lista_Usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_Lista_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Peliculas_TMDb`.`Usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Personaje` (
  `id_miembro` INT NOT NULL AUTO_INCREMENT,
  `personaje` VARCHAR(50) NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_miembro`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`PaisProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`PaisProduccion` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_pais`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Etiqueta` (
  `id_pelicula` INT NOT NULL,
  `id_etiqueta` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_etiqueta`),
  INDEX `FK_Pelicula_Etiqueta_Etiquetas` (`id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Etiqueta_Etiquetas`
    FOREIGN KEY (`id_etiqueta`)
    REFERENCES `Peliculas_TMDb`.`Etiquetas` (`id_etiqueta`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Pelicula_Etiqueta_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Genero` (
  `id_pelicula` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_genero`),
  INDEX `FK_Pelicula_Genero_Generos` (`id_genero` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Genero_Generos`
    FOREIGN KEY (`id_genero`)
    REFERENCES `Peliculas_TMDb`.`Generos` (`id_genero`),
  CONSTRAINT `FK_Pelicula_Genero_Peliculas`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Idioma` (
  `id_pelicula` INT NOT NULL,
  `id_idioma` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_idioma`),
  INDEX `FK_Pelicula_Idioma_Idiomas` (`id_idioma` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Idioma_Idiomas`
    FOREIGN KEY (`id_idioma`)
    REFERENCES `Peliculas_TMDb`.`Idiomas` (`id_idioma`),
  CONSTRAINT `FK_Pelicula_Idioma_Peliculas`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Crew` (
  `id_pelicula` INT NOT NULL,
  `id_credencial` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `genero` INT NULL,
  PRIMARY KEY (`id_pelicula`, `id_credencial`),
  CONSTRAINT `FK_Crew_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_PaisProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_PaisProduccion` (
  `id_pelicula` INT NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_pais`),
  INDEX `FK_Pelicula_PaisProduccion` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_PaisProduccion`
    FOREIGN KEY (`id_pais`)
    REFERENCES `Peliculas_TMDb`.`PaisProduccion` (`id_pais`),
  CONSTRAINT `FK_Pelicula_pelPais`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Productoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Productoras` (
  `id_productora` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_productora`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Pelicula_Productora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Pelicula_Productora` (
  `id_pelicula` INT NOT NULL,
  `id_productora` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_productora`),
  INDEX `FK_Pelicula_Productora` (`id_productora` ASC) VISIBLE,
  CONSTRAINT `FK_Pelicula_Productora`
    FOREIGN KEY (`id_productora`)
    REFERENCES `Peliculas_TMDb`.`Productoras` (`id_productora`),
  CONSTRAINT `FK_Pelicula_Pelicula_Productora`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Trabajo` (
  `id_trabajo` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(50) NULL,
  `trabajo` VARCHAR(50) NULL,
  PRIMARY KEY (`id_trabajo`));


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Crew_Personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Crew_Personaje` (
  `Crew_id_pelicula` INT NOT NULL,
  `Crew_id_credencial` VARCHAR(50) NOT NULL,
  `Personaje_id_miembro` INT NOT NULL,
  PRIMARY KEY (`Crew_id_pelicula`, `Crew_id_credencial`, `Personaje_id_miembro`),
  INDEX `fk_Crew_has_Personaje_Personaje1_idx` (`Personaje_id_miembro` ASC) VISIBLE,
  INDEX `fk_Crew_has_Personaje_Crew1_idx` (`Crew_id_pelicula` ASC, `Crew_id_credencial` ASC) VISIBLE,
  CONSTRAINT `fk_Crew_has_Personaje_Crew1`
    FOREIGN KEY (`Crew_id_pelicula` , `Crew_id_credencial`)
    REFERENCES `Peliculas_TMDb`.`Crew` (`id_pelicula` , `id_credencial`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crew_has_Personaje_Personaje1`
    FOREIGN KEY (`Personaje_id_miembro`)
    REFERENCES `Peliculas_TMDb`.`Personaje` (`id_miembro`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Crew_Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Crew_Trabajo` (
  `Crew_id_pelicula` INT NOT NULL,
  `Crew_id_credencial` VARCHAR(50) NOT NULL,
  `Trabajo_id_trabajo` INT NOT NULL,
  PRIMARY KEY (`Crew_id_pelicula`, `Crew_id_credencial`, `Trabajo_id_trabajo`),
  INDEX `fk_Crew_has_Trabajo_Trabajo1_idx` (`Trabajo_id_trabajo` ASC) VISIBLE,
  INDEX `fk_Crew_has_Trabajo_Crew1_idx` (`Crew_id_pelicula` ASC, `Crew_id_credencial` ASC) VISIBLE,
  CONSTRAINT `fk_Crew_has_Trabajo_Crew1`
    FOREIGN KEY (`Crew_id_pelicula` , `Crew_id_credencial`)
    REFERENCES `Peliculas_TMDb`.`Crew` (`id_pelicula` , `id_credencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crew_has_Trabajo_Trabajo1`
    FOREIGN KEY (`Trabajo_id_trabajo`)
    REFERENCES `Peliculas_TMDb`.`Trabajo` (`id_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Peliculas_TMDb`.`Lista_Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas_TMDb`.`Lista_Peliculas` (
  `id_lista` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  PRIMARY KEY (`id_lista`, `id_pelicula`),
  INDEX `FK_Pelicula_idx` (`id_pelicula` ASC) VISIBLE,
  CONSTRAINT `FK_lista`
    FOREIGN KEY (`id_lista`)
    REFERENCES `Peliculas_TMDb`.`Lista` (`id_lista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Pelicula`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Peliculas_TMDb`.`Peliculas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Peliculas_TMDb` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `Peliculas_TMDb`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
